# The following redirect is intended for use with most SPAs that handle
# routing internally.
#[build]
#  command = "yarn run build"
# functions = "functions"
#publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Headers= "*"
    Access-Control-Allow-Methods = 'GET, OPTIONS, POST, PUT'
    Access-Control-Allow-Origin = "*"